name: Build release binary
on:
  release:
    types: [published]
  #push:
  #  tags:
  #  - v*.*.*

jobs:
  build-win64:
    name: Build x64 Windows binary
    runs-on: windows-2019
    env:
      BUILD_ARCH: x64
      BUILD_LOGLEVEL: verbose
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/setup-python@v4
        id: py
        with:
          python-version: '2.7'
      - uses: actions/checkout@v3
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
      - run: move nexe\parpar.exe parpar.exe && 7z a -t7z -mx=9 parpar.7z parpar.exe
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} 
          asset_path: ./parpar.7z
          asset_name: parpar-${{ steps.get_release.outputs.tag_name }}-win64.7z
          asset_content_type: application/octet-stream
  
  build-linux-static:
    strategy:
      matrix:
        include:
        - target: x86_64-linux-musl
          arch: x64
          xz_bcj: --x86
          name: amd64
        - target: aarch64-linux-musl
          arch: arm64
          xz_bcj: # --arm64 # requires xz utils >=5.4 to decompress
          name: aarch64
        # disabled due to compiler crashing
        #- target: armv7l-linux-musleabihf
        #  arch: arm
        #  xz_bcj: --arm
        #  name: armhf
    name: Build ${{ matrix.name }} Linux static binary
    runs-on: ubuntu-latest
    env:
      BUILD_ARCH: ${{ matrix.arch }}
      BUILD_LOGLEVEL: verbose
      BUILD_CONFIGURE: '--with-arm-float-abi=hard --with-arm-fpu=vfpv3-d16'
      BUILD_STATIC: '--fully-static'
    steps:
      - uses: actions/checkout@v3
      - uses: Lesmiscore/musl-cross-compilers@jockie
        id: musl
        with:
          target: ${{ matrix.target }}
      - name: Install i386 dev
        run: |
          dpkg --add-architecture i386
          apt update
          apt install -y libstdc++-$(c++ -dumpversion)-dev:i386 libc6-dev:i386 g++-multilib
        if: ${{ matrix.arch }} == 'arm'
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
        env:
          CC: ${{ steps.musl.outputs.path }}/${{ matrix.target }}-cc
          CXX: ${{ steps.musl.outputs.path }}/${{ matrix.target }}-c++
          CC_host: cc
          CXX_host: c++
      - run: xz -9e ${{ matrix.xz_bcj }} --lzma2 nexe/parpar -C > parpar.xz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} 
          asset_path: ./parpar.xz
          asset_name: parpar-${{ steps.get_release.outputs.tag_name }}-linux-static-${{ matrix.name }}.xz
          asset_content_type: application/octet-stream

  build-linux-glibc:
    strategy:
      matrix:
        include:
        - xcc: 
          arch: x64
          xz_bcj: --x86
          name: amd64
        - xcc: aarch64-linux-gnu-
          arch: arm64
          xz_bcj: # --arm64 # requires xz utils >=5.4 to decompress
          name: aarch64
        - xcc: arm-linux-gnueabihf-
          arch: armhf
          xz_bcj: --arm
          name: armv7l
    name: Build ${{ matrix.name }} Linux glibc binary
    runs-on: ubuntu-20.04
    env:
      BUILD_ARCH: ${{ matrix.arch }}
      BUILD_LOGLEVEL: verbose
      BUILD_CONFIGURE: '--with-arm-float-abi=hard --with-arm-fpu=vfpv3-d16'
      BUILD_STATIC: '--partly-static'
    steps:
      - uses: actions/checkout@v3
      - uses: cyberjunk/gha-ubuntu-cross@v2
        with:
          arch: ${{ matrix.arch }}
        if: ${{ matrix.arch }} != 'x64'
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
        env:
          CC: ${{ matrix.xcc }}gcc
          CXX: ${{ matrix.xcc }}g++
          CC_host: cc
          CXX_host: c++
      - run: xz -9e ${{ matrix.xz_bcj }} --lzma2 nexe/parpar -C > parpar.xz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} 
          asset_path: ./parpar.xz
          asset_name: parpar-${{ steps.get_release.outputs.tag_name }}-linux-glibc2.31-${{ matrix.name }}.xz
          asset_content_type: application/octet-stream

  build-mac-x64:
    name: Build x64 MacOS binary
    runs-on: macos-latest
    env:
      BUILD_ARCH: x64
      BUILD_LOGLEVEL: verbose
    steps:
      - uses: actions/checkout@v3
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
      - run: xz -9e --x86 --lzma2 nexe/parpar -C > parpar.xz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} 
          asset_path: ./parpar.xz
          asset_name: parpar-${{ steps.get_release.outputs.tag_name }}-macos-x64.xz
          asset_content_type: application/octet-stream

  build-mac-arm64:
    name: Build arm64 MacOS binary
    runs-on: ubuntu-latest
    env:
      BUILD_ARCH: arm64
      BUILD_LOGLEVEL: verbose
    steps:
      - uses: mbround18/setup-osxcross@v1
        with:
          osx-version: "12.3"
      - uses: actions/checkout@v3
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
        env:
          CC: oa64e-clang
          CXX: oa64e-clang++
          CC_host: cc
          CXX_host: c++
      - run: xz -9e --lzma2 nexe/parpar -C > parpar.xz
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} 
          asset_path: ./parpar.xz
          asset_name: parpar-${{ steps.get_release.outputs.tag_name }}-macos-arm64e.xz
          asset_content_type: application/octet-stream
