name: Build dev Linux-glibc amd64 binary
on:
  workflow_dispatch:

jobs:
  build-dev-linux-glibc-amd64:
    name: Build dev amd64 Linux glibc binary
    runs-on: ubuntu-20.04
    env:
      BUILD_ARCH: x64
      BUILD_LOGLEVEL: verbose
      BUILD_STATIC: '--partly-static'
    steps:
      - uses: actions/checkout@v3
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
      - run: xz -9e --x86 --lzma2 nexe/parpar -C > parpar.xz
      - uses: actions/upload-artifact@v3
        with:
          path: ./parpar.xz
          name: parpar-${{ github.ref_name }}-linux-glibc-amd64.7z
          retention-days: 5
