name: Build dev MacOS arm64 binary
on:
  workflow_dispatch:

jobs:
  build-dev-mac-arm64:
    name: Build dev arm64 MacOS binary
    runs-on: ubuntu-latest
    env:
      BUILD_ARCH: arm64
      BUILD_LOGLEVEL: verbose
    steps:
      - uses: mbround18/setup-osxcross@v1
        with:
          osx-version: "12.3"
      - uses: actions/checkout@v3
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
        env:
          CC: oa64e-clang
          CXX: oa64e-clang++
          CC_host: cc
          CXX_host: c++
      - run: xz -9e --lzma2 nexe/parpar -c > parpar.xz
      - uses: actions/upload-artifact@v3
        with:
          path: ./parpar.xz
          name: parpar-${{ github.ref_name }}-macos-arm64e.7z
          retention-days: 5
