name: Build dev Linux-glibc armv7l binary
on:
  workflow_dispatch:

jobs:
  build-dev-linux-glibc-armv7l:
    name: Build dev armv7l Linux glibc binary
    runs-on: ubuntu-20.04
    env:
      BUILD_ARCH: armhf
      BUILD_LOGLEVEL: verbose
      BUILD_STATIC: '--partly-static'
    steps:
      - uses: actions/checkout@v3
      - uses: cyberjunk/gha-ubuntu-cross@v2
        with:
          arch: 'armhf'
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
        env:
          CC: arm-linux-gnueabihf-gcc
          CXX: arm-linux-gnueabihf-g++
          CC_host: cc
          CXX_host: c++
      - run: xz -9e --lzma2 nexe/parpar -C > parpar.xz
      - uses: actions/upload-artifact@v3
        with:
          path: ./parpar.xz
          name: parpar-${{ github.ref_name }}-linux-glibc-armv7l.7z
          retention-days: 5
